import { ReviewStats } from "@/sections/TestimonialsSection/components/ReviewStats";

export const TestimonialsSection = () => {
  return (
    <div className="relative text-sm bg-blue-500 bg-[url('https://img-4-cdn.airdroid.com/assets/img/parentalControl/home/bg_review@1-2e37a01d1a.5x.png')] bg-no-repeat bg-contain caret-transparent leading-[21px] bg-center mb-10 px-5 py-[60px] md:text-base md:leading-6 md:mb-[120px] md:pt-[110px] md:pb-[120px] md:px-10 before:accent-auto before:bg-[url('https://img-5-cdn.airdroid.com/assets/img/parentalControl/home/bg_review_up@1-b4982f9f7d.5x.png')] before:bg-top before:bg-no-repeat before:bg-contain before:caret-transparent before:text-black before:block before:text-sm before:not-italic before:normal-nums before:font-normal before:h-20 before:tracking-[normal] before:leading-[21px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-full before:z-[4] before:border-separate before:left-0 before:-top-px before:font-poppins before:md:text-base before:md:h-[100px] before:md:leading-6 after:accent-auto after:bg-[url('https://img-1-cdn.airdroid.com/assets/img/parentalControl/home/bg_review_down@1-4807d350c7.5x.png')] after:bg-bottom after:bg-no-repeat after:bg-contain after:caret-transparent after:text-black after:block after:text-sm after:not-italic after:normal-nums after:font-normal after:h-20 after:tracking-[normal] after:leading-[21px] after:list-outside after:list-disc after:pointer-events-auto after:absolute after:text-start after:indent-[0px] after:normal-case after:visible after:w-full after:z-[4] after:border-separate after:left-0 after:-bottom-px after:font-poppins after:md:text-base after:md:h-[100px] after:md:leading-6">
      <div className="relative text-sm caret-transparent leading-[21px] z-[3] md:text-base md:leading-6 before:accent-auto before:bg-[url('https://img-2-cdn.airdroid.com/assets/img/parentalControl/home/bg_review_left@1-65e78bb646.5x.png')] before:bg-no-repeat before:bg-contain before:caret-transparent before:text-black before:block before:text-sm before:not-italic before:normal-nums before:font-normal before:h-[72px] before:tracking-[normal] before:leading-[21px] before:list-outside before:list-disc before:pointer-events-auto before:absolute before:text-start before:indent-[0px] before:normal-case before:visible before:w-[294px] before:z-[-1] before:border-separate before:-left-5 before:-bottom-20 before:font-poppins before:md:text-base before:md:h-[120px] before:md:leading-6 before:md:w-[400px] before:md:-left-10 before:md:-bottom-40 after:accent-auto after:bg-[url('https://img-3-cdn.airdroid.com/assets/img/parentalControl/home/bg_review_right@1-992d377aae.5x.png')] after:bg-no-repeat after:bg-contain after:caret-transparent after:text-black after:block after:text-sm after:not-italic after:normal-nums after:font-normal after:h-[72px] after:tracking-[normal] after:leading-[21px] after:list-outside after:list-disc after:pointer-events-auto after:absolute after:text-start after:indent-[0px] after:normal-case after:visible after:w-[116px] after:z-[-1] after:border-separate after:-right-5 after:-bottom-20 after:font-poppins after:md:bottom-[-140px] after:md:text-base after:md:h-[120px] after:md:leading-6 after:md:w-[200px] after:md:-right-10">
        <h2 className="relative text-white text-2xl font-semibold caret-transparent tracking-[normal] leading-[31.2px] max-w-[1000px] text-center z-[1] mb-12 mx-auto md:text-[32px] md:tracking-[1px] md:leading-[41.6px] md:mb-[60px]">
          Your Trusted Digital Parenting Assistant
        </h2>
        <ReviewStats />
        <div className="relative text-sm items-center caret-transparent flex justify-center leading-[21px] mt-4 mb-5 mx-auto md:text-base md:leading-6 md:mt-5">
          <a
            href="/reviews/Watcher-parental-control/"
            className="text-white text-sm font-semibold caret-transparent block leading-[21px] md:text-base md:leading-6 after:accent-auto after:bg-[url('https://img-3-cdn.airdroid.com/assets/img/personal/banner/ic_link_next-724a556cf5.png')] after:bg-center after:bg-no-repeat after:bg-contain after:caret-transparent after:text-white after:inline-block after:text-sm after:not-italic after:normal-nums after:font-semibold after:h-[22px] after:tracking-[normal] after:leading-[21px] after:list-outside after:list-disc after:pointer-events-auto after:text-start after:indent-[0px] after:normal-case after:align-top after:visible after:w-[22px] after:ml-3 after:border-separate after:font-poppins after:md:text-base after:md:leading-6 hover:underline"
          >
            More reviews
          </a>
        </div>
      </div>
    </div>
  );
};
